require "user.plugins"
require "user.options"
require "user.keymaps"
require "user.cmp"
require "user.lsp" -- when a directory is required like this then lua will look for a init.lua in the dir and "source" that
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.bufferline"
require "user.toggleterm"
require "user.nvim-tree"
require "user.telescope"
require "user.indent_blankline"
require "user.which-key"
require "user.orgmode"
